export const regionsByCountry = {
  gb: [
    { value: "London, UK", label: "London, UK" },
    { value: "South East England, UK", label: "South East England, UK" },
    { value: "North West England, UK", label: "North West England, UK" },
    { value: "Eastern England, UK", label: "Eastern England, UK" },
    { value: "South West England, UK", label: "South West England, UK" },
    { value: "West Midlands, UK", label: "West Midlands, UK" },
    {
      value: "Yorkshire And The Humber, UK",
      label: "Yorkshire And The Humber, UK",
    },
    { value: "East Midlands, UK", label: "East Midlands, UK" },
    { value: "Scotland, UK", label: "Scotland, UK" },
    { value: "Wales, UK", label: "Wales, UK" },
    { value: "North East England, UK", label: "North East England, UK" },
    { value: "Northern Ireland, UK", label: "Northern Ireland, UK" },
    { value: "Channel Isles, UK", label: "Channel Isles, UK" },
    { value: "Isle Of Man, UK", label: "Isle Of Man, UK" },
  ],
  at: [
    { value: "Wien, Österreich", label: "Wien, Österreich" },
    {
      value: "Oberösterreich, Österreich",
      label: "Oberösterreich, Österreich",
    },
    {
      value: "Niederösterreich, Österreich",
      label: "Niederösterreich, Österreich",
    },
    { value: "Steiermark, Österreich", label: "Steiermark, Österreich" },
    { value: "Tirol, Österreich", label: "Tirol, Österreich" },
    { value: "Salzburg, Österreich", label: "Salzburg, Österreich" },
    { value: "Vorarlberg, Österreich", label: "Vorarlberg, Österreich" },
    { value: "Kärnten, Österreich", label: "Kärnten, Österreich" },
    { value: "Burgenland, Österreich", label: "Burgenland, Österreich" },
  ],
  au: [
    {
      value: "New South Wales, Australia",
      label: "New South Wales, Australia",
    },
    { value: "Queensland, Australia", label: "Queensland, Australia" },
    { value: "Victoria, Australia", label: "Victoria, Australia" },
    {
      value: "Western Australia, Australia",
      label: "Western Australia, Australia",
    },
    {
      value: "South Australia, Australia",
      label: "South Australia, Australia",
    },
    {
      value: "Australian Capital Territory, Australia",
      label: "Australian Capital Territory, Australia",
    },
    { value: "Tasmania, Australia", label: "Tasmania, Australia" },
    {
      value: "Northern Territory, Australia",
      label: "Northern Territory, Australia",
    },
    { value: "Norfolk Island, Australia", label: "Norfolk Island, Australia" },
  ],
  br: [
    { value: "Sudeste, Brasil", label: "Sudeste, Brasil" },
    { value: "Sul, Brasil", label: "Sul, Brasil" },
    { value: "Nordeste, Brasil", label: "Nordeste, Brasil" },
    { value: "Centro-Oeste, Brasil", label: "Centro-Oeste, Brasil" },
    { value: "Norte, Brasil", label: "Norte, Brasil" },
  ],
  be: [
    {
      value: "Antwerpen (Provincie), België",
      label: "Antwerpen (Provincie), België",
    },
    {
      value: "Oost-Vlaanderen (Provincie), België",
      label: "Oost-Vlaanderen (Provincie), België",
    },
    {
      value: "West-Vlaanderen (Provincie), België",
      label: "West-Vlaanderen (Provincie), België",
    },
    {
      value: "Vlaams-Brabant (Provincie), België",
      label: "Vlaams-Brabant (Provincie), België",
    },
    { value: "Brussel (Regio), België", label: "Brussel (Regio), België" },
    {
      value: "Henegouwen (Provincie), België",
      label: "Henegouwen (Provincie), België",
    },
    {
      value: "Limburg (Provincie), België",
      label: "Limburg (Provincie), België",
    },
    { value: "Luik (Provincie), België", label: "Luik (Provincie), België" },
    {
      value: "Waals-Brabant (Provincie), België",
      label: "Waals-Brabant (Provincie), België",
    },
    { value: "Namen (Provincie), België", label: "Namen (Provincie), België" },
    {
      value: "Luxemburg (Provincie), België",
      label: "Luxemburg (Provincie), België",
    },
  ],
  fr: [
    { value: "Ile-de-France, France", label: "Ile-de-France, France" },
    {
      value: "Auvergne-Rhône-Alpes, France",
      label: "Auvergne-Rhône-Alpes, France",
    },
    {
      value: "Nouvelle-Aquitaine, France",
      label: "Nouvelle-Aquitaine, France",
    },
    { value: "Occitanie, France", label: "Occitanie, France" },
    { value: "Grand-Est, France", label: "Grand-Est, France" },
    { value: "Pays de la Loire, France", label: "Pays de la Loire, France" },
    {
      value: "Provence-Alpes-Côte d'Azur, France",
      label: "Provence-Alpes-Côte d'Azur, France",
    },
    { value: "Hauts-De-France, France", label: "Hauts-De-France, France" },
    { value: "Bretagne, France", label: "Bretagne, France" },
    { value: "Normandie, France", label: "Normandie, France" },
    {
      value: "Bourgogne-Franche-Comté, France",
      label: "Bourgogne-Franche-Comté, France",
    },
    { value: "Centre, France", label: "Centre, France" },
    { value: "DOM-TOM, France", label: "DOM-TOM, France" },
    { value: "Corse, France", label: "Corse, France" },
  ],
  de: [
    {
      value: "Nordrhein-Westfalen, Deutschland",
      label: "Nordrhein-Westfalen, Deutschland",
    },
    { value: "Bayern, Deutschland", label: "Bayern, Deutschland" },
    {
      value: "Baden-Württemberg, Deutschland",
      label: "Baden-Württemberg, Deutschland",
    },
    {
      value: "Niedersachsen, Deutschland",
      label: "Niedersachsen, Deutschland",
    },
    { value: "Hessen, Deutschland", label: "Hessen, Deutschland" },
    { value: "Berlin, Deutschland", label: "Berlin, Deutschland" },
    {
      value: "Rheinland-Pfalz, Deutschland",
      label: "Rheinland-Pfalz, Deutschland",
    },
    { value: "Sachsen, Deutschland", label: "Sachsen, Deutschland" },
    { value: "Hamburg, Deutschland", label: "Hamburg, Deutschland" },
    {
      value: "Schleswig-Holstein, Deutschland",
      label: "Schleswig-Holstein, Deutschland",
    },
    { value: "Thüringen, Deutschland", label: "Thüringen, Deutschland" },
    { value: "Brandenburg, Deutschland", label: "Brandenburg, Deutschland" },
    {
      value: "Sachsen-Anhalt, Deutschland",
      label: "Sachsen-Anhalt, Deutschland",
    },
    {
      value: "Mecklenburg-Vorpommern, Deutschland",
      label: "Mecklenburg-Vorpommern, Deutschland",
    },
    { value: "Bremen, Deutschland", label: "Bremen, Deutschland" },
    { value: "Saarland, Deutschland", label: "Saarland, Deutschland" },
  ],
  es: [
    { value: "Cataluña, España", label: "Cataluña, España" },
    {
      value: "Comunidad de Madrid, España",
      label: "Comunidad de Madrid, España",
    },
    { value: "Andalucía, España", label: "Andalucía, España" },
    {
      value: "Comunidad Valenciana, España",
      label: "Comunidad Valenciana, España",
    },
    { value: "País Vasco, España", label: "País Vasco, España" },
    { value: "Galicia, España", label: "Galicia, España" },
    {
      value: "Castilla-La Mancha, España",
      label: "Castilla-La Mancha, España",
    },
    { value: "Castilla y León, España", label: "Castilla y León, España" },
    { value: "Canarias, España", label: "Canarias, España" },
    { value: "Aragón, España", label: "Aragón, España" },
    { value: "Región de Murcia, España", label: "Región de Murcia, España" },
    { value: "Islas Baleares, España", label: "Islas Baleares, España" },
    {
      value: "Principado de Asturias, España",
      label: "Principado de Asturias, España",
    },
    { value: "Navarra, España", label: "Navarra, España" },
    { value: "Cantabria, España", label: "Cantabria, España" },
    { value: "La Rioja, España", label: "La Rioja, España" },
    { value: "Extremadura, España", label: "Extremadura, España" },
    { value: "Ceuta, España", label: "Ceuta, España" },
    { value: "Melilla, España", label: "Melilla, España" },
  ],

  ca: [
    { value: "Ontario, Canada", label: "Ontario, Canada" },
    { value: "Québec, Canada", label: "Québec, Canada" },
    { value: "British Columbia, Canada", label: "British Columbia, Canada" },
    { value: "Alberta, Canada", label: "Alberta, Canada" },
    { value: "Nova Scotia, Canada", label: "Nova Scotia, Canada" },
    { value: "Saskatchewan, Canada", label: "Saskatchewan, Canada" },
    { value: "Manitoba, Canada", label: "Manitoba, Canada" },
    { value: "New Brunswick, Canada", label: "New Brunswick, Canada" },
    {
      value: "Newfoundland & Labrador, Canada",
      label: "Newfoundland & Labrador, Canada",
    },
    {
      value: "Prince Edward Island, Canada",
      label: "Prince Edward Island, Canada",
    },
    { value: "Yukon, Canada", label: "Yukon, Canada" },
    {
      value: "Northwest Territories, Canada",
      label: "Northwest Territories, Canada",
    },
    { value: "Nunavut, Canada", label: "Nunavut, Canada" },
  ],
  ch: [
    { value: "Zurich", label: "Zürich" },
    { value: "Bern", label: "Bern" },
    { value: "Aargau", label: "Aargau" },
    { value: "Vaud", label: "Waadt" },
    { value: "Lucerne", label: "Luzern" },
    { value: "Geneva", label: "Genf" },
    { value: "St. Gallen", label: "St.Gallen" },
    { value: "Solothurn", label: "Solothurn" },
    { value: "Basel-Stadt", label: "Basel-Stadt" },
    { value: "Thurgau", label: "Thurgau" },
    { value: "Basel-Landschaft", label: "Basel-Landschaft" },
    { value: "Graubunden", label: "Graubünden" },
    { value: "Valais", label: "Wallis" },
    { value: "Zug", label: "Zug" },
    { value: "Fribourg", label: "Freiburg" },
    { value: "Appenzell Ausserrhoden", label: "Appenzell Ausserrhoden" },
    { value: "Ticino", label: "Tessin" },
    { value: "Schwyz", label: "Schwyz" },
    { value: "Neuchatel", label: "Neuenburg" },
    { value: "Schaffhausen", label: "Schaffhausen" },
    { value: "Jura", label: "Jura" },
    { value: "Nidwalden", label: "Nidwalden" },
    { value: "Obwalden", label: "Obwalden" },
    { value: "Uri", label: "Uri" },
    { value: "Glarus", label: "Glarus" },
    { value: "Appenzell Innerrhoden", label: "Appenzell Innerrhoden" },
  ],
  in: [
    { value: "Karnataka, India", label: "Karnataka, India" },
    { value: "Maharashtra, India", label: "Maharashtra, India" },
    { value: "Telangana, India", label: "Telangana, India" },
    { value: "Tamil Nadu, India", label: "Tamil Nadu, India" },
    { value: "Gujarat, India", label: "Gujarat, India" },
    { value: "Delhi, India", label: "Delhi, India" },
    { value: "Uttar Pradesh, India", label: "Uttar Pradesh, India" },
    { value: "Haryana, India", label: "Haryana, India" },
    { value: "Rajasthan, India", label: "Rajasthan, India" },
    { value: "West Bengal, India", label: "West Bengal, India" },
    { value: "Kerala, India", label: "Kerala, India" },
    { value: "Madhya Pradesh, India", label: "Madhya Pradesh, India" },
    { value: "Punjab, India", label: "Punjab, India" },
    { value: "Chhattisgarh, India", label: "Chhattisgarh, India" },
    {
      value: "Dadra and Nagar Haveli, India",
      label: "Dadra and Nagar Haveli, India",
    },
    { value: "Andhra Pradesh, India", label: "Andhra Pradesh, India" },
    { value: "Chandigarh, India", label: "Chandigarh, India" },
    { value: "Orissa, India", label: "Orissa, India" },
    { value: "Goa, India", label: "Goa, India" },
    { value: "Uttarakhand, India", label: "Uttarakhand, India" },
    { value: "Bihar, India", label: "Bihar, India" },
    { value: "Assam, India", label: "Assam, India" },
    { value: "Jharkhand, India", label: "Jharkhand, India" },
    { value: "Himachal Pradesh, India", label: "Himachal Pradesh, India" },
    { value: "Jammu and Kashmir, India", label: "Jammu and Kashmir, India" },
    { value: "Puducherry, India", label: "Puducherry, India" },
    { value: "Daman and Diu, India", label: "Daman and Diu, India" },
    { value: "Arunachal Pradesh, India", label: "Arunachal Pradesh, India" },
    { value: "Meghalaya, India", label: "Meghalaya, India" },
    {
      value: "Andaman and Nicobar Islands, India",
      label: "Andaman and Nicobar Islands, India",
    },
    { value: "Manipur, India", label: "Manipur, India" },
    { value: "Nagaland, India", label: "Nagaland, India" },
    { value: "Tripura, India", label: "Tripura, India" },
    { value: "Mizoram, India", label: "Mizoram, India" },
    { value: "Lakshadweep, India", label: "Lakshadweep, India" },
    { value: "Sikkim, India", label: "Sikkim, India" },
  ],
  it: [
    { value: "Lombardia, Italia", label: "Lombardia, Italia" },
    { value: "Veneto, Italia", label: "Veneto, Italia" },
    { value: "Emilia-Romagna, Italia", label: "Emilia-Romagna, Italia" },
    { value: "Piemonte, Italia", label: "Piemonte, Italia" },
    { value: "Lazio, Italia", label: "Lazio, Italia" },
    { value: "Toscana, Italia", label: "Toscana, Italia" },
    { value: "Campania, Italia", label: "Campania, Italia" },
    { value: "Sicilia, Italia", label: "Sicilia, Italia" },
    { value: "Puglia, Italia", label: "Puglia, Italia" },
    { value: "Marche, Italia", label: "Marche, Italia" },
    {
      value: "Friuli-Venezia Giulia, Italia",
      label: "Friuli-Venezia Giulia, Italia",
    },
    { value: "Liguria, Italia", label: "Liguria, Italia" },
    { value: "Abruzzo, Italia", label: "Abruzzo, Italia" },
    { value: "Calabria, Italia", label: "Calabria, Italia" },
    { value: "Sardegna, Italia", label: "Sardegna, Italia" },
    {
      value: "Trentino-Alto Adige, Italia",
      label: "Trentino-Alto Adige, Italia",
    },
    { value: "Umbria, Italia", label: "Umbria, Italia" },
    { value: "Basilicata, Italia", label: "Basilicata, Italia" },
    { value: "Molise, Italia", label: "Molise, Italia" },
    { value: "Valle d'Aosta, Italia", label: "Valle d'Aosta, Italia" },
  ],
  mx: [
    { value: "Jalisco, México", label: "Jalisco, México" },
    { value: "Ciudad de México, México", label: "Ciudad de México, México" },
    { value: "Puebla, México", label: "Puebla, México" },
    { value: "Baja California, México", label: "Baja California, México" },
    { value: "Guanajuato, México", label: "Guanajuato, México" },
    { value: "Veracruz, México", label: "Veracruz, México" },
    { value: "Sonora, México", label: "Sonora, México" },
    { value: "Nuevo León, México", label: "Nuevo León, México" },
    { value: "Aguascalientes, México", label: "Aguascalientes, México" },
    { value: "Quintana Roo, México", label: "Quintana Roo, México" },
    { value: "Chihuahua, México", label: "Chihuahua, México" },
    {
      value: "Coahuila de Zaragoza, México",
      label: "Coahuila de Zaragoza, México",
    },
    { value: "Tamaulipas, México", label: "Tamaulipas, México" },
    { value: "Hidalgo, México", label: "Hidalgo, México" },
    { value: "Morelos, México", label: "Morelos, México" },
    {
      value: "Baja California Sur, México",
      label: "Baja California Sur, México",
    },
    { value: "Estado de México, México", label: "Estado de México, México" },
    { value: "Colima, México", label: "Colima, México" },
    { value: "Chiapas, México", label: "Chiapas, México" },
    { value: "Querétaro, México", label: "Querétaro, México" },
    { value: "Sinaloa, México", label: "Sinaloa, México" },
    { value: "Tabasco, México", label: "Tabasco, México" },
    { value: "Oaxaca, México", label: "Oaxaca, México" },
    { value: "Tlaxcala, México", label: "Tlaxcala, México" },
    { value: "Durango, México", label: "Durango, México" },
    { value: "Campeche, México", label: "Campeche, México" },
    { value: "Nayarit, México", label: "Nayarit, México" },
    { value: "Guerrero, México", label: "Guerrero, México" },
    { value: "Zacatecas, México", label: "Zacatecas, México" },
    { value: "San Luis Potosí, México", label: "San Luis Potosí, México" },
    { value: "Yucatán, México", label: "Yucatán, México" },
    {
      value: "Michoacán de Ocampo, México",
      label: "Michoacán de Ocampo, México",
    },
  ],
  nl: [
    { value: "Zuid-Holland, Nederland", label: "Zuid-Holland, Nederland" },
    { value: "Noord-Brabant, Nederland", label: "Noord-Brabant, Nederland" },
    { value: "Noord-Holland, Nederland", label: "Noord-Holland, Nederland" },
    { value: "Gelderland, Nederland", label: "Gelderland, Nederland" },
    {
      value: "Provincie Utrecht, Nederland",
      label: "Provincie Utrecht, Nederland",
    },
    { value: "Overijssel, Nederland", label: "Overijssel, Nederland" },
    { value: "Limburg, Nederland", label: "Limburg, Nederland" },
    { value: "Friesland, Nederland", label: "Friesland, Nederland" },
    { value: "Drenthe, Nederland", label: "Drenthe, Nederland" },
    { value: "Flevoland, Nederland", label: "Flevoland, Nederland" },
    {
      value: "Provincie Groningen, Nederland",
      label: "Provincie Groningen, Nederland",
    },
    { value: "Zeeland, Nederland", label: "Zeeland, Nederland" },
  ],
  nz: [
    { value: "North Island, New Zealand", label: "North Island, New Zealand" },
    { value: "South Island, New Zealand", label: "South Island, New Zealand" },
  ],
  pl: [
    { value: "mazowieckie, Polska", label: "mazowieckie, Polska" },
    { value: "śląskie, Polska", label: "śląskie, Polska" },
    { value: "małopolskie, Polska", label: "małopolskie, Polska" },
    { value: "dolnośląskie, Polska", label: "dolnośląskie, Polska" },
    { value: "wielkopolskie, Polska", label: "wielkopolskie, Polska" },
    { value: "pomorskie, Polska", label: "pomorskie, Polska" },
    { value: "łódzkie, Polska", label: "łódzkie, Polska" },
    {
      value: "zachodniopomorskie, Polska",
      label: "zachodniopomorskie, Polska",
    },
    {
      value: "kujawsko-pomorskie, Polska",
      label: "kujawsko-pomorskie, Polska",
    },
    { value: "podkarpackie, Polska", label: "podkarpackie, Polska" },
    { value: "lubelskie, Polska", label: "lubelskie, Polska" },
    { value: "opolskie, Polska", label: "opolskie, Polska" },
    { value: "lubuskie, Polska", label: "lubuskie, Polska" },
    { value: "podlaskie, Polska", label: "podlaskie, Polska" },
    {
      value: "warmińsko-mazurskie, Polska",
      label: "warmińsko-mazurskie, Polska",
    },
    { value: "świętokrzyskie, Polska", label: "świętokrzyskie, Polska" },
  ],
  sg: [
    { value: "Central, Singapore", label: "Central, Singapore" },
    { value: "North, Singapore", label: "North, Singapore" },
    { value: "West, Singapore", label: "West, Singapore" },
    { value: "East, Singapore", label: "East, Singapore" },
    { value: "North East, Singapore", label: "North East, Singapore" },
  ],
  za: [
    { value: "Gauteng, South Africa", label: "Gauteng, South Africa" },
    {
      value: "Western Cape, South Africa",
      label: "Western Cape, South Africa",
    },
    {
      value: "KwaZulu-Natal, South Africa",
      label: "KwaZulu-Natal, South Africa",
    },
    {
      value: "Eastern Cape, South Africa",
      label: "Eastern Cape, South Africa",
    },
    { value: "Free State, South Africa", label: "Free State, South Africa" },
    { value: "Limpopo, South Africa", label: "Limpopo, South Africa" },
    { value: "Mpumalanga, South Africa", label: "Mpumalanga, South Africa" },
    { value: "North West, South Africa", label: "North West, South Africa" },
    {
      value: "Northern Cape, South Africa",
      label: "Northern Cape, South Africa",
    },
  ],
};

export const getRegionsForCountry = (countryCode) => {
  return regionsByCountry[countryCode?.toLowerCase()] || [];
};

// Вспомогательная функция для проверки наличия регионов для страны
export const hasRegions = (countryCode) => {
  return !!regionsByCountry[countryCode?.toLowerCase()];
};
